permalink: /:categories/:title
pages_list:       
        About: 'knowledge/about'
        Archive: 'knowledge/archive'
        Feed: 'knowledge/atom.xml'

collections:
        kb:
          output: true
